language: python
python:   
  - '3.8'
install:
  - pip install -r requirements-travis.txt
before_script:
- psql -c 'create database test_db;' -U postgres
services:
- postgresql
script: 
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
deploy:
  provider: heroku
  api_key: 027deb56-50c4-47c3-891f-5e73f29df39c
  app: quick-thooters
  on:
    repo: uva-cs3240-s20/project-102-quickthooters
